mongo_data:
    image: mongo:3.0
    volumes:
        - /data/db-birdcage

database:
    image: mongo:3.0
    ports:
        - "27017:27017"
    volumes_from:
        - mongo_data
    command: --smallfiles
